
SELECT * FROM MBSASMDTDT0.TBSUFURSS WHERE SS_ALLO_VNO_NO NOT IN (SELECT SS_ALLO_VNO_NO FROM MBSASSTD.TBSUFURSS);

SELECT * FROM MBSASDEV.TB_PARAMETER WHERE dataset = 'dsMainList';
SELECT COL_4, COL_5, COL_7, CASE WHEN sum(COL_19)<0 THEN 0 else sum(COL_19) END AS AVAIL_QTY FROM MBSASDEV.TB_PARAMETER WHERE dataset = 'dsMainList' AND SEQ > 0 GROUP BY COL_4, COL_5, COL_7;



-- EIV 업데이트 
 UPDATE
	MBSASSTD.TBSIAUEIV UEIV
SET
	UEIV.GNRL_GDS_STK_QTY = UEIV.GNRL_GDS_STK_QTY + NVL((
		SELECT
			CASE
				WHEN sum(COL_19)<0 THEN 0 ELSE sum(COL_19)
			END AS AVAIL_QTY
		FROM
			MBSASDEV.TB_PARAMETER
		WHERE
			dataset = 'dsMainList'
			AND SEQ > 0
			AND COL_4 = UEIV.BRN_CD 
			AND COL_5 = UEIV.WHS_CD 
			AND COL_7 = UEIV.PTNO
		GROUP BY COL_4, COL_5, COL_7
		),	0);
