---------------------------------------------------------------------------------------------------------------------------------
-- UFW0030U S/S 판매
---------------------------------------------------------------------------------------------------------------------------------

-- MDT 버전
CREATE TABLE MBSASMDTBAKUPT.TBSURSSMDT_20240202 AS (
SELECT
		URSF.ALLO_BRN_CD 		AS ALLO_BRN_CD,
		URSF.SS_SL_DCD 			AS SS_SL_DCD,
		URSF.RO_HKC_DCD 		AS RO_HKC_DCD,
		URSF.RO_DCD 			AS RO_DCD,
		URSF.RPR_RO_PTR_INFO_CD AS RPR_RO_PTR_INFO_CD,
		URSF.RPR_RO_XLT_CUST_CD AS RPR_RO_XLT_CUST_CD,
		URSS.PTNO 				AS PTNO,
		URSS.PT_ENG_NM 			AS PT_ENG_NM,
		URSS.SRC_CD 			AS SRC_CD,
		URSS.CMDL_CD 			AS CMDL_CD,
		URSS.BSA_GRP_CD 		AS BSA_GRP_CD,
		URSS.SL_QTY 			AS SL_QTY,
		URSS.TBCK_QTY 			AS TBCK_QTY,
		URSS.SL_UPC 			AS SL_UPC,
		URSS.MVC 				AS MVC,
		URSS.MVC_DIFF_AMT 		AS MVC_DIFF_AMT,
		URSS.GRS_CST 			AS GRS_CST,
		URSS.RTL_SL_TCD 		AS RTL_SL_TCD,
		URSS.HEPS_SL_YN 		AS HEPS_SL_YN,
		URSS.SND_WHS_CD 		AS SND_WHS_CD,
		URSS.HMC_UPC 			AS HMC_UPC,
		URSS.HKC_DCD 			AS HKC_DCD,
		URSS.RTL_UPC 			AS RTL_UPC,
		URSS.ITM_DCD 			AS ITM_DCD,
		URSS.DC_YN 				AS DC_YN,
		URSS.RTL_DCRT 			AS RTL_DCRT
	FROM
		(SELECT * FROM MBSASSTD.TBSUFURSF WHERE SS_ALLO_VNO_NO NOT IN (SELECT SS_ALLO_VNO_NO FROM MBSASMDTBAK.TBSUFURSF)) URSF,
		MBSASSTD.TBSUFURSS URSS
	WHERE
		URSF.SS_ALLO_VNO_NO = URSS.SS_ALLO_VNO_NO ) WITH DATA;

-- 10061 건
SELECT count(*) FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202;
	
-- DT0 버전
CREATE TABLE MBSASMDTBAKUPT.TBSURSSASIS_20240202 AS (
SELECT
		URSF.ALLO_BRN_CD 		AS ALLO_BRN_CD,
		URSF.SS_SL_DCD 			AS SS_SL_DCD,
		URSF.RO_HKC_DCD 		AS RO_HKC_DCD,
		URSF.RO_DCD 			AS RO_DCD,
		URSF.RPR_RO_PTR_INFO_CD AS RPR_RO_PTR_INFO_CD,
		URSF.RPR_RO_XLT_CUST_CD AS RPR_RO_XLT_CUST_CD,
		URSS.PTNO 				AS PTNO,
		URSS.PT_ENG_NM 			AS PT_ENG_NM,
		URSS.SRC_CD 			AS SRC_CD,
		URSS.CMDL_CD 			AS CMDL_CD,
		URSS.BSA_GRP_CD 		AS BSA_GRP_CD,
		URSS.SL_QTY 			AS SL_QTY,
		URSS.TBCK_QTY 			AS TBCK_QTY,
		URSS.SL_UPC 			AS SL_UPC,
		URSS.MVC 				AS MVC,
		URSS.MVC_DIFF_AMT 		AS MVC_DIFF_AMT,
		URSS.GRS_CST 			AS GRS_CST,
		URSS.RTL_SL_TCD 		AS RTL_SL_TCD,
		URSS.HEPS_SL_YN 		AS HEPS_SL_YN,
		URSS.SND_WHS_CD 		AS SND_WHS_CD,
		URSS.HMC_UPC 			AS HMC_UPC,
		URSS.HKC_DCD 			AS HKC_DCD,
		URSS.RTL_UPC 			AS RTL_UPC,
		URSS.ITM_DCD 			AS ITM_DCD,
		URSS.DC_YN 				AS DC_YN,
		URSS.RTL_DCRT 			AS RTL_DCRT
	FROM
		(SELECT * FROM MBSASMDTDT0.TBSUFURSF WHERE SS_ALLO_VNO_NO NOT IN (SELECT SS_ALLO_VNO_NO FROM MBSASMDTBAK.TBSUFURSF)) URSF,
		MBSASSTD.TBSUFURSS URSS
	WHERE
		URSF.SS_ALLO_VNO_NO = URSS.SS_ALLO_VNO_NO ) WITH DATA;

-- 10061 건
SELECT count(*) FROM MBSASMDTBAKUPT.TBSURSSASIS_20240202;

-- MDT버전과 ASIS 버전 비교 쿼리	
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A 
 WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);
	
-- 현대, RO ID: 6이 아닌 것 , UDPM.소가 = HMC_UPC
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	UDPM.HKC_DCD AS UDPM_HKC ,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	UDPM.RTL_BS_PRC*0.78,
	UDPM.GRS_CST*1.,
	UDPM.SRC_CD,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A, MBSASSTD.TBSTAUDPM UDPM 
 WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND M.PTNO = UDPM.PTNO 
   AND (M.RO_HKC_DCD = 'H' AND M.RO_DCD not IN ('6') AND UDPM.RTL_BS_PRC != M.HMC_UPC )
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);
	
-- 현대, RO ID: 6, UDPM.소가*0.78 = HMC_UPC
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	UDPM.HKC_DCD AS UDPM_HKC ,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	UDPM.RTL_BS_PRC*0.78,
	UDPM.GRS_CST*1.,
	UDPM.SRC_CD,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A, MBSASSTD.TBSTAUDPM UDPM 
 WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND M.PTNO = UDPM.PTNO 
   AND (M.RO_HKC_DCD = 'H' AND M.RO_DCD  IN ('6') AND UDPM.RTL_BS_PRC*0.78 != M.HMC_UPC )
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);
	
-- 기아, RO ID : W, UDPM소가*0.78 = HMC_UPC
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	UDPM.HKC_DCD AS UDPM_HKC ,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	UDPM.RTL_BS_PRC*0.78,
	UDPM.GRS_CST,
	UDPM.SRC_CD,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A, MBSASSTD.TBSTAUDPM UDPM 
 WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND M.PTNO = UDPM.PTNO 
   AND M.RO_HKC_DCD = 'K' AND M.RO_DCD='W'
   AND UDPM.RTL_BS_PRC*0.78 != M.HMC_UPC
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);

-- 기아, RO ID : W가 아닌 것, UDPM소가 = HMC_UPC
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	UDPM.HKC_DCD AS UDPM_HKC ,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	UDPM.RTL_BS_PRC,
	UDPM.GRS_CST,
	UDPM.SRC_CD,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A, MBSASSTD.TBSTAUDPM UDPM 
 WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND M.PTNO = UDPM.PTNO 
   AND M.RO_HKC_DCD = 'K' AND M.RO_DCD !='W'
   AND UDPM.RTL_BS_PRC != M.HMC_UPC
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);
	
SELECT  UDPM.PTNO, UDPM.RTL_BS_PRC             /* 소매기준가격 */                                                    
                  , UDPM.MAV_UPC                /* 이동평균단가 */                                                    
                  , UDPM.PUNT_RQRD_QTY          /* 대수당소요수량 */
                  , UDPM.MC_CD                  /* MC코드:통제코드구분 */    
                  , UDPM.PFNC_CD                /* 주기능코드*/
                  , UDPM.PTR_PRC                /* 우대가격 */  
                  , UDPM.WS_BS_PRC              /* 도매기준가격 */
                  , UDPM.GRS_CST                /* 총원가 */
                  , UDPM.BFCG_PTNO              /* 변경전부품번호*/ 
                  , UDPM.PT_ACC_DCD             /* 부품용품구분코드*/
                  , SUBSTRING(RTRIM(UDPM.PTNO), (LENGTH(RTRIM(UDPM.PTNO))-2)) AS QQH_PTNO  
                  , UBMT.MCTR_CD
                  , UDPM.MBS_CMDL_CD 
                  , UDPM.ITM_DCD 
               FROM MBSASSTD.TBSIAUBMT UBMT     /* 사업소기본 */
         INNER JOIN MBSASSTD.TBSTAUDPM UDPM     /* 내수부품기본 */
                 ON UDPM.HKC_DCD IN(UBMT.HKC_DCD, 'C') /* 현대기아구분코드 */  
    LEFT OUTER JOIN MBSASSTD.TBSUAMDCP MDCP     /* 부품자기인증내역 */                            
                 ON MDCP.PTNO    =  UDPM.PTNO   /* 부품번호 */ 
    LEFT OUTER JOIN MBSASSTD.TBSTATPNC TPNC     /* PNC코드 */
                 ON TPNC.PNC_CD  = UDPM.PNC_CD  /* PNC코드 */
    LEFT OUTER JOIN MBSASSTD.TBSTAMCAR MCAR     /* 모비스차종코드 */
                 ON MCAR.MBS_CMDL_CD  = UDPM.MBS_CMDL_CD  /* 모비스차종코드 */                 
              WHERE UBMT.BRN_CD  = 'RCB'     
                AND UDPM.PTNO   IN('98360F2600')     
                AND UBMT.DEL_DT  = '';
                
               
---------------------------------------------------------------------------------------------------------------------------------               
-- UFW0020U C/S 판매
---------------------------------------------------------------------------------------------------------------------------------

-- 1. MDT     
CREATE TABLE MBSASMDTBAKUPT.TBSURCSMDT_20240219 AS (          
SELECT 
	URCF.ALLO_BRN_CD  		-- 조치사업소코드
	,URCF.ALLO_SNO			-- 조치일련번호
	,URCF.RTL_SL_DCD  		-- 소매판매구분코드
	,URCF.SMY_VND_CD  		-- 소액업체코드
	,URCF.SMY_VND_CUST_NM 	-- 소액업체명
	,URCS.PTNO				-- PTNO
	,URCS.PT_ENG_NM
	,URCS.RTL_SL_TCD		-- 소매판매유형코드
	,URCS.RTL_DCRT			-- 소매할인율
	,URCS.SL_UPC			-- 판매단가
	,URCS.MVC				-- 이동단가
	,URCS.RTL_UPC			-- 소매단가
FROM
	(SELECT * FROM MBSASSTD.TBSUFURCF WHERE CS_ALLO_VNO_NO NOT IN (SELECT CS_ALLO_VNO_NO FROM MBSASMDTBAK.TBSUFURCF)) URCF,
	MBSASSTD.TBSUFURCS URCS
WHERE
	URCF.CS_ALLO_VNO_NO = URCS.CS_ALLO_VNO_NO) WITH DATA;

-- 534건
SELECT count(*) FROM MBSASMDTBAKUPT.TBSURCSMDT_20240219 WHERE RTL_SL_TCD = 'FJ';

-- 2. DT0    
CREATE TABLE MBSASMDTBAKUPT.TBSURCSASIS_20240219 AS (           
SELECT 
	URCF.ALLO_BRN_CD  		-- 조치사업소코드
	,URCF.ALLO_SNO			-- 조치일련번호
	,URCF.RTL_SL_DCD  		-- 소매판매구분코드
	,URCF.SMY_VND_CD  		-- 소액업체코드
	,URCF.SMY_VND_CUST_NM 	-- 소액업체명
	,URCS.PTNO				-- PTNO
	,URCS.PT_ENG_NM
	,URCS.RTL_SL_TCD		-- 소매판매유형코드
	,URCS.RTL_DCRT			-- 소매할인율
	,URCS.SL_UPC			-- 판매단가
	,URCS.MVC				-- 이동단가
	,URCS.RTL_UPC			-- 소매단가
FROM
	(SELECT * FROM MBSASMDTDT0.TBSUFURCF WHERE CS_ALLO_VNO_NO NOT IN (SELECT CS_ALLO_VNO_NO FROM MBSASMDTBAK.TBSUFURCF)) URCF,
	MBSASMDTDT0.TBSUFURCS URCS
WHERE
	URCF.CS_ALLO_VNO_NO = URCS.CS_ALLO_VNO_NO) WITH DATA;
	
-- 543건
SELECT count(*) FROM MBSASMDTBAKUPT.TBSURCSASIS_20240219 WHERE RTL_SL_TCD = 'FJ';


-- 가격 비교
SELECT 
	MDT.ALLO_BRN_CD,
	MDT.ALLO_SNO,
	MDT.PTNO,
	MDT.RTL_SL_TCD,
	MDT.MVC , 		-- 이동단가
	ASIS.MVC,		-- 이동단다
	MDT.RTL_UPC ,	-- 소매단가
	ASIS.RTL_UPC,	-- 소매단가
	MDT.SL_UPC ,	-- 판매단가
	ASIS.SL_UPC		-- 판매단가
  FROM MBSASMDTBAKUPT.TBSURCSMDT_20240219 MDT, MBSASMDTBAKUPT.TBSURCSASIS_20240219 ASIS
 WHERE MDT.ALLO_BRN_CD = ASIS.ALLO_BRN_CD
   AND MDT.ALLO_SNO = ASIS.ALLO_SNO
   AND MDT.PTNO = ASIS.PTNO
   AND (MDT.RTL_UPC != ASIS.RTL_UPC OR MDT.SL_UPC!=ASIS.SL_UPC)
   AND MDT.RTL_SL_TCD = 'FJ';