SELECT * FROM mbsasdev.TB_PARAMETER WHERE appl_id = 'UFW0030U' AND dataset='dsMainList' AND COL_7= '3.64E+45' ORDER BY seq; -- 
SELECT PTNO,PT_ENG_NM,MAV_UPC FROM mbsasstd.TBSTAUDPM WHERE ptno LIKE '%364%' AND PT_ENG_NM LIKE '%ONBOARD CHARGER ASSY%'; 
UPDATE mbsasdev.TB_PARAMETER SET COL_7 = '364000E040' WHERE appl_id = 'UFW0030U' AND dataset='dsMainList' AND COL_7= '3.64E+45';

SELECT * FROM (
SELECT PARM.seq, PARM.COL_7, UDPM.* 
  FROM mbsasdev.TB_PARAMETER PARM LEFT OUTER JOIN mbsasstd.TBSTAUDPM UDPM ON PARM.COL_7 = UDPM.PTNO
 WHERE PARM.APPL_ID = 'UFW0030U' AND PARM.dataset='dsMainList' AND PARM.SEQ>0
 ORDER BY PARM.SEQ) 
 WHERE PTNO IS null;