SELECT *
FROM MBSASNON.TBSIABLOG
WHERE 1 = 1
AND STK_BCH_PGM_ID = 'ITB0230U'
--AND BCH_PRCT_LOG_DCD = 'E'
AND BCH_PRCT_LOG_CN LIKE '%(getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])%'
AND SUBSTRING(CRT_DTM, 0, 11) LIKE '2023-12-%';

SELECT *
FROM MBSASNON.TBSIABLOG
WHERE 1 = 1
AND STK_BCH_PGM_ID = 'ITB0230U'
--AND BCH_PRCT_LOG_DCD = 'E'
--AND BCH_PRCT_LOG_CN LIKE '%(getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])%'
AND BCH_PRCT_LOG_CN LIKE '%0222100813%'
AND SUBSTRING(CRT_DTM, 0, 11) LIKE '2023-12-%'
ORDER BY CRT_DTM DESC;

PTNO : 1125306206B, ReqQty : 40 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 0222100813, ReqQty : 2 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 0501212601, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 05203GI100, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 091103K000, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 09130G9000, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 091314H000, ReqQty : 4 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 09139S1600, ReqQty : 2 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 09149L1050, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 091804F100, ReqQty : 2 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 091804F100, ReqQty : 2 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 091807L500, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])

SELECT * FROM mbsasstd.TBSLAULOC;
SELECT * FROM mbsasstd.TBSLAULOC WHERE ptno = '2824552021';
SELECT * FROM mbsasstd.TBSIAUEIV WHERE ptno = '2824552021';
SELECT * FROM mbsasstd.TBSIAUBIV WHERE ptno = '2824552021';

-- BIV와 SUM(LOC) 비교
SELECT
	ULOC.MCTR_CD,
	ULOC.WHS_CD,
	ULOC.AVS_QTY,
	UBIV.BRN_CD,
	UBIV.WHS_CD,
	UBIV.PTNO,
	UBIV.GNRL_GDS_STK_QTY + UBIV.STK_CTL_QTY + UBIV.KIT_GDS_STK_QTY + UBIV.POI_GDS_STK_QTY AS UBIV_AVS_QTY
FROM
	(SELECT MCTR_CD,WHS_CD,PTNO, sum(AVS_QTY) AS AVS_QTY FROM mbsasstd.TBSLAULOC GROUP BY mctr_cd, WHS_CD, PTNO) ULOC,
	mbsasstd.TBSIAUBIV UBIV
WHERE
	ULOC.MCTR_CD = UBIV.BRN_CD 
	AND ULOC.WHS_CD = UBIV.WHS_CD
	AND ULOC.PTNO = UBIV.PTNO
	AND ULOC.AVS_QTY != (UBIV.GNRL_GDS_STK_QTY + UBIV.STK_CTL_QTY + UBIV.KIT_GDS_STK_QTY + UBIV.POI_GDS_STK_QTY)
	;
	
-- BIV vs LOC
SELECT
	ULOC.MCTR_CD,
	ULOC.WHS_CD,
	ULOC.LOC_NO, 
	ULOC.PRI_CD,
	ULOC.AVS_QTY,
	UBIV.BRN_CD,
	UBIV.WHS_CD,
	UBIV.PTNO,
	UBIV.GNRL_GDS_STK_QTY + UBIV.STK_CTL_QTY + UBIV.KIT_GDS_STK_QTY + UBIV.POI_GDS_STK_QTY AS UBIV_AVS_QTY
FROM
	mbsasstd.TBSLAULOC ULOC,
	mbsasstd.TBSIAUBIV UBIV
WHERE
	ULOC.MCTR_CD = UBIV.BRN_CD 
	AND ULOC.WHS_CD = UBIV.WHS_CD
	AND ULOC.PTNO = UBIV.PTNO
	AND UBIV.PTNO = '091103K000'
	-- AND ULOC.AVS_QTY < (UBIV.GNRL_GDS_STK_QTY + UBIV.STK_CTL_QTY + UBIV.KIT_GDS_STK_QTY + UBIV.POI_GDS_STK_QTY)
	;

SELECT * FROM MBSASMDTBAK.TBSTAUDPM WHERE ptno ='091103K000';

UPDATE mbsasstd.TBSLAULOC SET AVS_QTY = '50000' WHERE mctr_cd LIKE 'M%';

PTNO : 091103K000, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
PTNO : 091103K000, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])

PTNO ; 091103K000 시작되는 부품
초과재고코드 적용수량4 => +  BRN_CD ; SCA, PTNO ; 091103K000, tmpArgQty : 1.00
TRF 셋팅 시 주 로케이션  = PTNO ; 091103K000 MlocNo() ; 11A094807P
BIV Update = PTNO ; 091103K000 BRN_CD ; SCA
초과재고코드 적용수량 2 => + BRN_CD ; SCK, PTNO ; 091103K000, tmpArgQty : 0.00
초과재고코드 적용수량4 => +  BRN_CD ; CCA, PTNO ; 091103K000, tmpArgQty : 3.00
TRF 셋팅 시 주 로케이션  = PTNO ; 091103K000 MlocNo() ; 21A063002C
PTNO : 091103K000, ReqQty : 1 (getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])
BIV Update = PTNO ; 091103K000 BRN_CD ; CCA

SELECT *
FROM MBSASNON.TBSIABLOG
WHERE 1 = 1
AND STK_BCH_PGM_ID = 'ITB0230U'
--AND BCH_PRCT_LOG_DCD = 'E'
--AND BCH_PRCT_LOG_CN LIKE '%(getErrCd:62, getErrMsgId: IP0015, getErrParam : [입력수량이 LOC 가용재고 수량])%'
AND BCH_PRCT_LOG_CN LIKE '%091103K000%'
AND SUBSTRING(CRT_DTM, 0, 11) LIKE '2024-01-%';

SELECT * FROM mbsasstd.TBSLAULOC WHERE PTNO = '091103K000';




-------------해외영업
-- 오류 확인 
SELECT *
FROM MBSASSTD.TBSHEOLOG
WHERE ERR_MSG LIKE '%배분오류 (60)%'
;


-- MEIM vs ULOC 비교 
SELECT
	ULOC.MCTR_CD,
	ULOC.WHS_CD,
	ULOC.AVS_QTY,
	MEIM.BRN_CD,
	MEIM.WHS_CD,
	MEIM.PTNO,
	MEIM.GNRL_GDS_STK_QTY + MEIM.KIT_GDS_STK_QTY + MEIM.POI_GDS_STK_QTY + MEIM.OUTB_ALLO_QTY AS MEIM_AVS_QTY
FROM
	(SELECT MCTR_CD,WHS_CD,PTNO, sum(AVS_QTY) AS AVS_QTY FROM mbsasstd.TBSLAULOC GROUP BY mctr_cd, WHS_CD, PTNO) ULOC,
	mbsasstd.TBSIAMEIM MEIM
WHERE
	ULOC.MCTR_CD = MEIM.BRN_CD 
	AND ULOC.WHS_CD = MEIM.WHS_CD
	AND ULOC.PTNO = MEIM.PTNO
	AND ULOC.AVS_QTY != (MEIM.GNRL_GDS_STK_QTY + MEIM.KIT_GDS_STK_QTY + MEIM.POI_GDS_STK_QTY + MEIM.OUTB_ALLO_QTY)
	;

-- MEIM vs ULOC 비교 
SELECT
	ULOC.MCTR_CD,
	ULOC.WHS_CD,
	ULOC.PRI_CD, 
	ULOC.AVS_QTY,
	MEIM.BRN_CD,
	MEIM.WHS_CD,
	MEIM.PTNO,
	MEIM.GNRL_GDS_STK_QTY + MEIM.KIT_GDS_STK_QTY + MEIM.POI_GDS_STK_QTY + MEIM.OUTB_ALLO_QTY AS MEIM_AVS_QTY
FROM
	mbsasstd.TBSLAULOC ULOC,
	mbsasstd.TBSIAMEIM MEIM
WHERE
	ULOC.MCTR_CD = MEIM.BRN_CD 
	AND ULOC.WHS_CD = MEIM.WHS_CD
	AND ULOC.PTNO = MEIM.PTNO
	AND MEIM.PTNO ='283212B800';
	;
	
-- MALD 확인 (60에러)
SELECT
	MORP.ORD_NO,
	MORP.ORD_PTNO,
	MORP.DST_SCCD,
	MALD.CTR_CD,
	MALD.DSTB_ERR_CD
FROM
	MBSASSTD.TBSHEMORP MORP,
	MBSASSTD.TBSHEMALD MALD
WHERE
	MORP.ORD_NO = MALD.ORD_NO
	AND MORP.ORD_LN = MALD.ORD_LN
	AND MALD.DSTB_ERR_CD = '60' ;
