-- TBSUFURSF
select * from MBSASMDTDT0.TBSUFURSF
minus
select * from MBSASMDTBAK.TBSUFURSF;

-- TBSUFURSS
select * from MBSASMDTDT0.TBSUFURSS
minus
select * from MBSASMDTBAK.TBSUFURSS;


-- MDT 버전
CREATE TABLE MBSASMDTBAKUPT.TBSURSSMDT_20240202 AS (
SELECT
		URSF.ALLO_BRN_CD 		AS ALLO_BRN_CD,
		URSF.SS_SL_DCD 			AS SS_SL_DCD,
		URSF.RO_HKC_DCD 		AS RO_HKC_DCD,
		URSF.RO_DCD 			AS RO_DCD,
		URSF.RPR_RO_PTR_INFO_CD AS RPR_RO_PTR_INFO_CD,
		URSF.RPR_RO_XLT_CUST_CD AS RPR_RO_XLT_CUST_CD,
		URSS.PTNO 				AS PTNO,
		URSS.PT_ENG_NM 			AS PT_ENG_NM,
		URSS.SRC_CD 			AS SRC_CD,
		URSS.CMDL_CD 			AS CMDL_CD,
		URSS.BSA_GRP_CD 		AS BSA_GRP_CD,
		URSS.SL_QTY 			AS SL_QTY,
		URSS.TBCK_QTY 			AS TBCK_QTY,
		URSS.SL_UPC 			AS SL_UPC,
		URSS.MVC 				AS MVC,
		URSS.MVC_DIFF_AMT 		AS MVC_DIFF_AMT,
		URSS.GRS_CST 			AS GRS_CST,
		URSS.RTL_SL_TCD 		AS RTL_SL_TCD,
		URSS.HEPS_SL_YN 		AS HEPS_SL_YN,
		URSS.SND_WHS_CD 		AS SND_WHS_CD,
		URSS.HMC_UPC 			AS HMC_UPC,
		URSS.HKC_DCD 			AS HKC_DCD,
		URSS.RTL_UPC 			AS RTL_UPC,
		URSS.ITM_DCD 			AS ITM_DCD,
		URSS.DC_YN 				AS DC_YN,
		URSS.RTL_DCRT 			AS RTL_DCRT
	FROM
		(SELECT * FROM MBSASSTD.TBSUFURSF WHERE SS_ALLO_VNO_NO NOT IN (SELECT SS_ALLO_VNO_NO FROM MBSASMDTBAK.TBSUFURSF)) URSF,
		MBSASSTD.TBSUFURSS URSS
	WHERE
		URSF.SS_ALLO_VNO_NO = URSS.SS_ALLO_VNO_NO ) WITH DATA;

-- DT0 버전
CREATE TABLE MBSASMDTBAKUPT.TBSURSSASIS_20240202 AS (
SELECT
		URSF.ALLO_BRN_CD 		AS ALLO_BRN_CD,
		URSF.SS_SL_DCD 			AS SS_SL_DCD,
		URSF.RO_HKC_DCD 		AS RO_HKC_DCD,
		URSF.RO_DCD 			AS RO_DCD,
		URSF.RPR_RO_PTR_INFO_CD AS RPR_RO_PTR_INFO_CD,
		URSF.RPR_RO_XLT_CUST_CD AS RPR_RO_XLT_CUST_CD,
		URSS.PTNO 				AS PTNO,
		URSS.PT_ENG_NM 			AS PT_ENG_NM,
		URSS.SRC_CD 			AS SRC_CD,
		URSS.CMDL_CD 			AS CMDL_CD,
		URSS.BSA_GRP_CD 		AS BSA_GRP_CD,
		URSS.SL_QTY 			AS SL_QTY,
		URSS.TBCK_QTY 			AS TBCK_QTY,
		URSS.SL_UPC 			AS SL_UPC,
		URSS.MVC 				AS MVC,
		URSS.MVC_DIFF_AMT 		AS MVC_DIFF_AMT,
		URSS.GRS_CST 			AS GRS_CST,
		URSS.RTL_SL_TCD 		AS RTL_SL_TCD,
		URSS.HEPS_SL_YN 		AS HEPS_SL_YN,
		URSS.SND_WHS_CD 		AS SND_WHS_CD,
		URSS.HMC_UPC 			AS HMC_UPC,
		URSS.HKC_DCD 			AS HKC_DCD,
		URSS.RTL_UPC 			AS RTL_UPC,
		URSS.ITM_DCD 			AS ITM_DCD,
		URSS.DC_YN 				AS DC_YN,
		URSS.RTL_DCRT 			AS RTL_DCRT
	FROM
		(SELECT * FROM MBSASMDTDT0.TBSUFURSF WHERE SS_ALLO_VNO_NO NOT IN (SELECT SS_ALLO_VNO_NO FROM MBSASMDTBAK.TBSUFURSF)) URSF,
		MBSASSTD.TBSUFURSS URSS
	WHERE
		URSF.SS_ALLO_VNO_NO = URSS.SS_ALLO_VNO_NO ) WITH DATA;
	
-- MDT버전과 ASIS 버전 비교 쿼리	
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A
WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);

-- 비교 조건 수정
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A
WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);
		
SELECT 
	M.ALLO_BRN_CD,
	M.SS_SL_DCD,
	M.RO_HKC_DCD,
	UDPM.HKC_DCD AS UDPM_HKC ,
	M.RO_DCD,
	M.RPR_RO_PTR_INFO_CD,
	M.RPR_RO_XLT_CUST_CD,
	M.PTNO,
	M.PT_ENG_NM,
	M.SL_QTY AS SL_QTY0,
	A.SL_QTY AS SL_QTY1,
	M.SL_UPC AS SL_UPC0,
	A.SL_UPC AS SL_UPC1,
	M.MVC AS MVC0,
	A.MVC AS MVC1,
	M.GRS_CST AS GRS_CST0,
	A.GRS_CST AS GRS_CST1,
	UDPM.RTL_BS_PRC,
	UDPM.GRS_CST*1.2,
	M.HMC_UPC AS HMC_UPC0,
	A.HMC_UPC AS HMC_UPC1
  FROM MBSASMDTBAKUPT.TBSURSSMDT_20240202 M, MBSASMDTBAKUPT.TBSURSSASIS_20240202 A, MBSASSTD.TBSTAUDPM UDPM 
WHERE M.ALLO_BRN_CD = A.ALLO_BRN_CD 
   AND M.SS_SL_DCD = A.SS_SL_DCD
   AND M.RO_HKC_DCD = A.RO_HKC_DCD
   AND M.RO_DCD = A.RO_DCD
   AND M.PTNO = A.PTNO
   AND M.SL_QTY = A.SL_QTY
   AND M.RPR_RO_PTR_INFO_CD = A.RPR_RO_PTR_INFO_CD
   AND M.RPR_RO_XLT_CUST_CD = A.RPR_RO_XLT_CUST_CD
   AND M.PTNO = UDPM.PTNO 
   AND (M.RO_HKC_DCD = 'H' AND M.RO_DCD  IN ('3','6') AND UDPM.RTL_BS_PRC != M.HMC_UPC )
   AND (M.SL_UPC !=	A.SL_UPC OR
		M.MVC != A.MVC OR
		M.GRS_CST != A.GRS_CST OR
		M.HMC_UPC != A.HMC_UPC);		