-- 수출만 한정으로 재산정 (BRN_CD lik 'E%', LT 컬럼은 비교 제외) 	
SELECT '일치건수' AS 구분,	
          count(*) AS 건수	
  FROM MBSASSTD.TBSIPMCVP MCVP1,	 
       MBSASMDTDT0.TBSIPMCVP MCVP0 	
 WHERE MCVP1.PTNO = MCVP0.PTNO 	
   AND MCVP1.VND_CD = MCVP0.VND_CD 	
   AND MCVP1.BRN_CD = MCVP0.BRN_CD	
   AND MCVP1.BRN_CD LIKE 'E%'	
   AND MCVP1.SFS_PRBT = MCVP0.SFS_PRBT	
   AND MCVP1.APLY_LT = MCVP0.APLY_LT	
   AND MCVP1.ROP_CFC = MCVP0.ROP_CFC	
   AND MCVP1.EOQ_CFC = MCVP0.EOQ_CFC	
   AND MCVP1.T_MOS = MCVP0.T_MOS	
 UNION ALL 	
SELECT '불일치건수' AS 구분,	
          count(*) AS 건수	
  FROM MBSASSTD.TBSIPMCVP MCVP1, 
       MBSASMDTDT0.TBSIPMCVP MCVP0 	
 WHERE (MCVP1.PTNO = MCVP0.PTNO 	
   AND MCVP1.VND_CD = MCVP0.VND_CD 	
   AND MCVP1.BRN_CD = MCVP0.BRN_CD)	
   AND MCVP1.BRN_CD LIKE 'E%'	
   AND (MCVP1.SFS_PRBT != MCVP0.SFS_PRBT	
   OR MCVP1.APLY_LT != MCVP0.APLY_LT	
   OR MCVP1.ROP_CFC != MCVP0.ROP_CFC	
   OR MCVP1.EOQ_CFC != MCVP0.EOQ_CFC	
   OR MCVP1.T_MOS != MCVP0.T_MOS	
  );	

 
 -- 임형국 수정 검증쿼리. 안전재고 확률에 case 적용
 SELECT '일치건수' AS 구분,
          count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1,
       MBSASMDTDT0.TBSIPMCVP MCVP0
WHERE MCVP1.PTNO = MCVP0.PTNO
   AND MCVP1.VND_CD = MCVP0.VND_CD
   AND MCVP1.BRN_CD = MCVP0.BRN_CD
   AND MCVP1.BRN_CD LIKE 'E%'
--   AND MCVP1.SFS_PRBT = MCVP0.SFS_PRBT
   AND (CASE WHEN MCVP1.PO_PLCY_CD IN ('D','E','N') THEN MCVP1.SFS_PRBT =0 ELSE MCVP1.SFS_PRBT = MCVP0.SFS_PRBT END)  -- D,E,N 의 경우 이행을 0으로 하기로 함
   AND MCVP1.APLY_LT = MCVP0.APLY_LT
   --AND MCVP1.LT = MCVP0.LT
   AND MCVP1.ROP_CFC = MCVP0.ROP_CFC
   AND MCVP1.EOQ_CFC = MCVP0.EOQ_CFC
   AND MCVP1.T_MOS = MCVP0.T_MOS
UNION ALL
SELECT '불일치건수' AS 구분,
          count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1,
       MBSASMDTDT0.TBSIPMCVP MCVP0
WHERE (MCVP1.PTNO = MCVP0.PTNO
   AND MCVP1.VND_CD = MCVP0.VND_CD
   AND MCVP1.BRN_CD = MCVP0.BRN_CD)
   AND MCVP1.BRN_CD LIKE 'E%'
--   AND (MCVP1.SFS_PRBT != MCVP0.SFS_PRBT
   AND ((CASE WHEN MCVP1.PO_PLCY_CD IN ('D','E','N') THEN MCVP1.SFS_PRBT <>0 ELSE MCVP1.SFS_PRBT != MCVP0.SFS_PRBT END)
   OR MCVP1.APLY_LT != MCVP0.APLY_LT
   --OR MCVP1.LT != MCVP0.LT
   OR MCVP1.ROP_CFC != MCVP0.ROP_CFC
   OR MCVP1.EOQ_CFC != MCVP0.EOQ_CFC
   OR MCVP1.T_MOS != MCVP0.T_MOS
  );
  
 -- 임형구 검증쿼리 2차. T_MOS에도 case 적용. 
 SELECT '일치건수' AS 구분,
          count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1,
       MBSASMDTDT0.TBSIPMCVP MCVP0
WHERE MCVP1.PTNO = MCVP0.PTNO
   AND MCVP1.VND_CD = MCVP0.VND_CD
   AND MCVP1.BRN_CD = MCVP0.BRN_CD
   AND MCVP1.BRN_CD LIKE 'E%'
--   AND MCVP1.SFS_PRBT = MCVP0.SFS_PRBT
   AND (CASE WHEN (MCVP1.PO_PLCY_CD IN ('D','E','N') AND MCVP1.POCF_YN<>'Y')THEN MCVP1.SFS_PRBT =0 ELSE MCVP1.SFS_PRBT = MCVP0.SFS_PRBT END)  -- D,E,N 의 경우 이행을 0으로 하기로 함
   AND MCVP1.APLY_LT = MCVP0.APLY_LT
   --AND MCVP1.LT = MCVP0.LT
   AND MCVP1.ROP_CFC = MCVP0.ROP_CFC
   AND MCVP1.EOQ_CFC = MCVP0.EOQ_CFC
--   AND MCVP1.T_MOS = MCVP0.T_MOS
   AND (CASE WHEN (MCVP1.PO_PLCY_CD IN ('D','E','N') AND MCVP1.POCF_YN<>'Y') THEN MCVP1.T_MOS =0 ELSE MCVP1.T_MOS = MCVP0.T_MOS END)
--   AND MCVP1.PTNO='91555M6170'
UNION ALL
SELECT '불일치건수' AS 구분,
          count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1,
       MBSASMDTDT0.TBSIPMCVP MCVP0
WHERE (MCVP1.PTNO = MCVP0.PTNO
   AND MCVP1.VND_CD = MCVP0.VND_CD
   AND MCVP1.BRN_CD = MCVP0.BRN_CD)
--   AND MCVP1.PTNO='91555M6170'
   AND MCVP1.BRN_CD LIKE 'E%'
--   AND (MCVP1.SFS_PRBT != MCVP0.SFS_PRBT
   AND ((CASE WHEN (MCVP1.PO_PLCY_CD IN ('D','E','N') AND MCVP1.POCF_YN<>'Y') THEN MCVP1.SFS_PRBT <>0 ELSE MCVP1.SFS_PRBT != MCVP0.SFS_PRBT END)
   OR MCVP1.APLY_LT != MCVP0.APLY_LT
   --OR MCVP1.LT != MCVP0.LT
   OR MCVP1.ROP_CFC != MCVP0.ROP_CFC
   OR MCVP1.EOQ_CFC != MCVP0.EOQ_CFC
--   OR MCVP1.T_MOS != MCVP0.T_MOS
   OR (CASE WHEN (MCVP1.PO_PLCY_CD IN ('D','E','N') AND MCVP1.POCF_YN<>'Y') THEN MCVP1.T_MOS <>0 ELSE MCVP1.T_MOS != MCVP0.T_MOS END)
  );
  
 
 
 