-- 결과 건수비교
SELECT '일치건수' AS 구분,
	count(*) AS 건수
  FROM MBSASSTD.TBSIPMVPM MVPM1,
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD
   AND MVPM1.PMI_PSBL_QTY=MVPM0.PMI_PSBL_QTY
   AND MVPM1.CMPT_MIL_QTY=MVPM0.CMPT_MIL_QTY
   AND MVPM1.CMPT_COP_QTY=MVPM0.CMPT_COP_QTY
   AND MVPM1.CMPT_POI_QTY=MVPM0.CMPT_POI_QTY
   AND MVPM1.PO_PLCY_CD=MVPM0.PO_PLCY_CD
   UNION ALL 
 SELECT '불일치건수' AS 구분,
	count(*) AS 건수
  FROM MBSASSTD.TBSIPMVPM MVPM1,
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD
   AND (MVPM1.PMI_PSBL_QTY!=MVPM0.PMI_PSBL_QTY
   OR MVPM1.CMPT_MIL_QTY!=MVPM0.CMPT_MIL_QTY
   OR MVPM1.CMPT_COP_QTY!=MVPM0.CMPT_COP_QTY
   OR MVPM1.CMPT_POI_QTY!=MVPM0.CMPT_POI_QTY
   OR MVPM1.PO_PLCY_CD!=MVPM0.PO_PLCY_CD)  
   ;
