---MDT_CAO
SELECT '일치건수' AS 구분,
          count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1,
       MBSASMDTDT0.TBSIPMCVP MCVP0 
 WHERE MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD
   AND MCVP1.BRN_CD LIKE 'E%'
   AND MCVP1.APLY_LT = MCVP0.APLY_LT
   AND MCVP1.ROP_CFC = MCVP0.ROP_CFC
   AND MCVP1.EOQ_CFC = MCVP0.EOQ_CFC
   AND MCVP1.ROP_QTY = MCVP0.ROP_QTY
   AND MCVP1.EOQ_QTY = MCVP0.EOQ_QTY
   AND MCVP1.MAX_STK_QTY = MCVP0.MAX_STK_QTY
   AND MCVP1.MAD_QTY = MCVP0.MAD_QTY
   AND (CASE WHEN MCVP0.PO_PLCY_CD IN ('P','R') THEN MCVP1.PO_PLCY_CD='E' WHEN MCVP0.PO_PLCY_CD='O' THEN MCVP1.PO_PLCY_CD='D' ELSE MCVP1.PO_PLCY_CD = MCVP0.PO_PLCY_CD END)
   AND (CASE WHEN (MCVP1.PO_PLCY_CD IN ('E','N') AND MCVP1.MA_FXD_YN<>'Y' AND MCVP1.SRTBL_NO IN ('IP036ZZZZ','IP055ZZZZ')) THEN MCVP1.PO_AMD_TCD ='' ELSE MCVP1.PO_AMD_TCD = MCVP0.PO_AMD_TCD END)
   AND (CASE WHEN (MCVP1.PO_PLCY_CD IN ('D','E','N') AND MCVP1.POCF_YN<>'Y' AND MCVP1.SRTBL_NO<>'IP004ZZZZ') THEN MCVP1.T_MOS =0 ELSE MCVP1.T_MOS = MCVP0.T_MOS END)
   AND (CASE WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HR36' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) = 'IP036'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HV40' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) = 'IP040'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) IN ('HU02','HU90') THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) = 'IP004'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HR55' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) = 'IP055'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HV42' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) = 'IP042'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HR56' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) = 'IP056'
            END)   
 UNION ALL 
SELECT '불일치건수' AS 구분,
          count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1,
       MBSASMDTDT0.TBSIPMCVP MCVP0 
 WHERE (MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD)
   AND MCVP1.BRN_CD LIKE 'E%'
   AND (
   MCVP1.APLY_LT != MCVP0.APLY_LT
   OR MCVP1.ROP_CFC != MCVP0.ROP_CFC
   OR MCVP1.EOQ_CFC != MCVP0.EOQ_CFC
   OR MCVP1.ROP_QTY != MCVP0.ROP_QTY
   OR MCVP1.EOQ_QTY != MCVP0.EOQ_QTY
   OR MCVP1.MAX_STK_QTY != MCVP0.MAX_STK_QTY
   OR MCVP1.MAD_QTY != MCVP0.MAD_QTY
   OR (CASE WHEN MCVP0.PO_PLCY_CD IN ('P','R') THEN MCVP1.PO_PLCY_CD!='E' WHEN MCVP0.PO_PLCY_CD='O' THEN MCVP1.PO_PLCY_CD!='D' ELSE MCVP1.PO_PLCY_CD != MCVP0.PO_PLCY_CD END)
   OR (CASE WHEN (MCVP1.PO_PLCY_CD IN ('E','N') AND MCVP1.MA_FXD_YN<>'Y' AND MCVP1.SRTBL_NO IN ('IP036ZZZZ','IP055ZZZZ')) THEN MCVP1.PO_AMD_TCD <>'' ELSE MCVP1.PO_AMD_TCD != MCVP0.PO_AMD_TCD END)
   OR (CASE WHEN (MCVP1.PO_PLCY_CD IN ('D','E','N') AND MCVP1.POCF_YN<>'Y' AND MCVP1.SRTBL_NO<>'IP004ZZZZ') THEN MCVP1.T_MOS <>0 ELSE MCVP1.T_MOS != MCVP0.T_MOS END)
   OR (CASE WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HR36' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) != 'IP036'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HV40' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) != 'IP040'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) IN ('HU02','HU90') THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) != 'IP004'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HR55' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) != 'IP055'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HV42' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) != 'IP042'
            WHEN SUBSTRING(MCVP0.SRTBL_NO,1,4) = 'HR56' THEN  SUBSTRING(MCVP1.SRTBL_NO,1,5) != 'IP056'
            END) 
)



---------------------PMI-----------------------------------
-----------------------------------------------------------     
            
 SELECT '일치건수' AS 구분,
count(*) AS 건수
  FROM MBSASSTD.TBSIPMVPM MVPM1,
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD
   AND MVPM1.BRN_CD IN ('EH0','EK0')
   AND MVPM1.CMPT_MIL_QTY = MVPM0.CMPT_MIL_QTY
   AND MVPM1.CMPT_COP_QTY = MVPM0.CMPT_COP_QTY
   AND MVPM1.MAX_STK_QTY = MVPM0.MAX_STK_QTY
   AND MVPM1.CMPT_POI_QTY= MVPM0.CMPT_POI_QTY
   AND MVPM1.MIL_QTY = MVPM0.MIL_QTY
   AND MVPM1.COP_QTY = MVPM0.COP_QTY
   AND MVPM1.POI_QTY = MVPM0.POI_QTY
   AND MVPM1.T_MOS = MVPM0.T_MOS 
   AND MVPM1.PO_PLCY_CD = MVPM0.PO_PLCY_CD
   AND MVPM1.PO_AMD_TCD = MVPM0.PO_AMD_TCD 
   AND MVPM1.MAD_QTY = MVPM0.MAD_QTY
   AND MVPM1.BS_VND_CD = MVPM0.BS_VND_CD
   AND (CASE WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HR36' THEN  MVPM1.APLY_SRTBL_SCR_NO = 'IP036'
            WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HV40' THEN  MVPM1.APLY_SRTBL_SCR_NO = 'IP040'
            WHEN MVPM0.APLY_SRTBL_SCR_NO IN ('HU02','HU90') THEN  MVPM1.APLY_SRTBL_SCR_NO = 'IP004'
            WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HR55' THEN  MVPM1.APLY_SRTBL_SCR_NO = 'IP055'
            WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HV42' THEN  MVPM1.APLY_SRTBL_SCR_NO = 'IP042'
            END)      
   UNION ALL 
 SELECT '불일치건수' AS 구분,
count(*) AS 건수
  FROM MBSASSTD.TBSIPMVPM MVPM1,
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD
   AND MVPM1.BRN_CD IN ('EH0','EK0')
   AND (
   MVPM1.CMPT_MIL_QTY != MVPM0.CMPT_MIL_QTY
   OR MVPM1.CMPT_COP_QTY != MVPM0.CMPT_COP_QTY
   OR MVPM1.MAX_STK_QTY != MVPM0.MAX_STK_QTY
   OR MVPM1.CMPT_POI_QTY!= MVPM0.CMPT_POI_QTY
   OR MVPM1.MIL_QTY != MVPM0.MIL_QTY
   OR MVPM1.COP_QTY != MVPM0.COP_QTY
   OR MVPM1.POI_QTY != MVPM0.POI_QTY
   OR MVPM1.T_MOS != MVPM0.T_MOS 
   OR MVPM1.PO_PLCY_CD!=MVPM0.PO_PLCY_CD
   OR MVPM1.PO_AMD_TCD != MVPM0.PO_AMD_TCD 
   OR MVPM1.MAD_QTY != MVPM0.MAD_QTY
   OR MVPM1.BS_VND_CD != MVPM0.BS_VND_CD
   OR (CASE WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HR36' THEN  MVPM1.APLY_SRTBL_SCR_NO != 'IP036'
            WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HV40' THEN  MVPM1.APLY_SRTBL_SCR_NO != 'IP040'
            WHEN MVPM0.APLY_SRTBL_SCR_NO IN ('HU02','HU90') THEN  MVPM1.APLY_SRTBL_SCR_NO != 'IP004'
            WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HR55' THEN  MVPM1.APLY_SRTBL_SCR_NO != 'IP055'
            WHEN MVPM0.APLY_SRTBL_SCR_NO = 'HV42' THEN  MVPM1.APLY_SRTBL_SCR_NO != 'IP042'
            END)   
   )  