-- TBSIPMCVP CAO재고부품기본

SELECT count(*) FROM MBSASSTD.TBSIPMCVP;

-- 계수 비교 쿼리 
SELECT MCVP1.PTNO 			--부품번호
	  ,MCVP1.VND_CD 			--업체코드	
	  ,MCVP1.BRN_CD 			--사업소코드
	  ,MCVP1.SFS_PRBT AS SFS_PRBT1		-- -1: 안전재고확률
	  ,MCVP0.SFS_PRBT AS SFS_PRBT0		-- 0: 안전재고확률
	  ,MCVP1.APLY_LT AS APLY_LT1		-- -1: APLY_LT
	  ,MCVP0.APLY_LT AS APLY_LT0		-- 0: APLY_LT
	  ,MCVP1.LT AS LT1		-- -1: LT
	  ,MCVP0.LT AS LT0		-- 0: LT
	  ,MCVP1.ROP_CFC AS ROP_CFC1		-- -1: ROP_CFC
	  ,MCVP0.ROP_CFC AS ROP_CFC0		-- 0: ROP_CFC
	  ,MCVP1.EOQ_CFC AS EOQ_CFC1		-- -1: EOQ_CFC
	  ,MCVP0.EOQ_CFC AS EOQ_CFC0		-- 0: EOQ_CFC
	  ,MCVP1.T_MOS AS T_MOS1		-- -1: T_MOS
	  ,MCVP0.T_MOS AS T_MOS0		-- 0: T_MOS
	  ,MCVP1.W1_OL_CFC AS W1_OL_CFC1		-- -1: W1_OL_CFC
	  ,MCVP0.W1_OL_CFC AS W1_OL_CFC0		-- 0: W1_OL_CFC
	  ,MCVP1.W2_OL_CFC AS W2_OL_CFC1		-- -1: W2_OL_CFC
	  ,MCVP0.W2_OL_CFC AS W2_OL_CFC0		-- 0: W2_OL_CFC
	  ,MCVP1.W3_OL_CFC AS W3_OL_CFC1		-- -1: W3_OL_CFC
	  ,MCVP0.W3_OL_CFC AS W3_OL_CFC0		-- 0: W3_OL_CFC
	  ,MCVP1.W4_OL_CFC AS W4_OL_CFC1		-- -1: W4_OL_CFC
	  ,MCVP0.W4_OL_CFC AS W4_OL_CFC0		-- 0: W4_OL_CFC
  FROM MBSASSTD.TBSIPMCVP MCVP1, 
       MBSASMDTDT0.TBSIPMCVP MCVP0 
 WHERE MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD;

-- D-0 and STD 결과 건수비교
SELECT '일치건수' AS 구분, 
		count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1, 
       MBSASMDTDT0.TBSIPMCVP MCVP0 
 WHERE MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD
   AND MCVP1.SFS_PRBT = MCVP0.SFS_PRBT
   AND MCVP1.APLY_LT = MCVP0.APLY_LT
   AND MCVP1.LT = MCVP0.LT
   AND MCVP1.ROP_CFC = MCVP0.ROP_CFC
   AND MCVP1.EOQ_CFC = MCVP0.EOQ_CFC
   AND MCVP1.T_MOS = MCVP0.T_MOS
   AND MCVP1.W1_OL_CFC = MCVP0.W1_OL_CFC
   AND MCVP1.W2_OL_CFC = MCVP0.W2_OL_CFC
   AND MCVP1.W3_OL_CFC = MCVP0.W3_OL_CFC
   AND MCVP1.W4_OL_CFC = MCVP0.W4_OL_CFC
 UNION ALL 
SELECT '불일치건수' AS 구분, 
		count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1, 
       MBSASMDTDT0.TBSIPMCVP MCVP0 
 WHERE (MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD)
   AND (MCVP1.SFS_PRBT != MCVP0.SFS_PRBT
   OR MCVP1.APLY_LT != MCVP0.APLY_LT
   OR MCVP1.LT != MCVP0.LT
   OR MCVP1.ROP_CFC != MCVP0.ROP_CFC
   OR MCVP1.EOQ_CFC != MCVP0.EOQ_CFC
   OR MCVP1.T_MOS != MCVP0.T_MOS
   OR MCVP1.W1_OL_CFC != MCVP0.W1_OL_CFC
   OR MCVP1.W2_OL_CFC != MCVP0.W2_OL_CFC
   OR MCVP1.W3_OL_CFC != MCVP0.W3_OL_CFC
   OR MCVP1.W4_OL_CFC != MCVP0.W4_OL_CFC);

  -- D-0 and BAK 결과 건수비교
SELECT '일치건수' AS 구분, 
		count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1, 
       MBSASMDTBAK.TBSIPMCVP MCVP0 
 WHERE MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD
   AND MCVP1.SFS_PRBT = MCVP0.SFS_PRBT
   AND MCVP1.APLY_LT = MCVP0.APLY_LT
   AND MCVP1.LT = MCVP0.LT
   AND MCVP1.ROP_CFC = MCVP0.ROP_CFC
   AND MCVP1.EOQ_CFC = MCVP0.EOQ_CFC
   AND MCVP1.T_MOS = MCVP0.T_MOS
   AND MCVP1.W1_OL_CFC = MCVP0.W1_OL_CFC
   AND MCVP1.W2_OL_CFC = MCVP0.W2_OL_CFC
   AND MCVP1.W3_OL_CFC = MCVP0.W3_OL_CFC
   AND MCVP1.W4_OL_CFC = MCVP0.W4_OL_CFC
 UNION ALL 
SELECT '불일치건수' AS 구분, 
		count(*) AS 건수
  FROM MBSASSTD.TBSIPMCVP MCVP1, 
       MBSASMDTBAK.TBSIPMCVP MCVP0 
 WHERE (MCVP1.PTNO = MCVP0.PTNO 
   AND MCVP1.VND_CD = MCVP0.VND_CD 
   AND MCVP1.BRN_CD = MCVP0.BRN_CD)
   AND (MCVP1.SFS_PRBT != MCVP0.SFS_PRBT
   OR MCVP1.APLY_LT != MCVP0.APLY_LT
   OR MCVP1.LT != MCVP0.LT
   OR MCVP1.ROP_CFC != MCVP0.ROP_CFC
   OR MCVP1.EOQ_CFC != MCVP0.EOQ_CFC
   OR MCVP1.T_MOS != MCVP0.T_MOS
   OR MCVP1.W1_OL_CFC != MCVP0.W1_OL_CFC
   OR MCVP1.W2_OL_CFC != MCVP0.W2_OL_CFC
   OR MCVP1.W3_OL_CFC != MCVP0.W3_OL_CFC
   OR MCVP1.W4_OL_CFC != MCVP0.W4_OL_CFC);
   
  
  

-- TBSIPMVPM PMI재고부품기본
  SELECT count(*) FROM MBSASSTD.TBSIPMVPM;
  SELECT * FROM MBSASSTD.TBSIPMVPM;
 
 -- 계수 비교 쿼리 
SELECT MVPM1.PTNO 			--부품번호
	  ,MVPM1.VND_CD 			--업체코드	
	  ,MVPM1.BRN_CD 			--사업소코드
	  ,MVPM1.PMI_PSBL_QTY AS PMI_PSBL_QTY1		-- -1: PMI_PSBL_QTY
	  ,MVPM0.PMI_PSBL_QTY AS PMI_PSBL_QTY0		-- 0: PMI_PSBL_QTY
	  ,MVPM1.CMPT_MIL_QTY AS CMPT_MIL_QTY1		-- -1: CMPT_MIL_QTY
	  ,MVPM0.CMPT_MIL_QTY AS CMPT_MIL_QTY0		-- 0: CMPT_MIL_QTY
	  ,MVPM1.CMPT_COP_QTY AS CMPT_COP_QTY1		-- -1: CMPT_COP_QTY
	  ,MVPM0.CMPT_COP_QTY AS CMPT_COP_QTY0		-- 0: CMPT_COP_QTY
	  ,MVPM1.CMPT_POI_QTY AS CMPT_POI_QTY1		-- -1: CMPT_POI_QTY
	  ,MVPM0.CMPT_POI_QTY AS CMPT_POI_QTY0		-- 0: CMPT_POI_QTY
	  ,MVPM1.PO_PLCY_CD AS PO_PLCY_CD1		-- -1: PO_PLCY_CD
	  ,MVPM0.PO_PLCY_CD AS PO_PLCY_CD0		-- 0: PO_PLCY_CD
  FROM MBSASSTD.TBSIPMVPM MVPM1, 
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD;
   
  -- D-0 and STD 결과 건수비교
SELECT '일치건수' AS 구분, 
		count(*) AS 건수
  FROM MBSASSTD.TBSIPMVPM MVPM1, 
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD
   AND MVPM1.PMI_PSBL_QTY=MVPM0.PMI_PSBL_QTY
   AND MVPM1.CMPT_MIL_QTY=MVPM0.CMPT_MIL_QTY
   AND MVPM1.CMPT_MIL_QTY=MVPM0.CMPT_MIL_QTY
   AND MVPM1.CMPT_POI_QTY=MVPM0.CMPT_POI_QTY
   AND MVPM1.PO_PLCY_CD=MVPM0.PO_PLCY_CD
   UNION ALL 
 SELECT '불일치건수' AS 구분, 
		count(*) AS 건수
  FROM MBSASSTD.TBSIPMVPM MVPM1, 
       MBSASMDTDT0.TBSIPMVPM MVPM0 
 WHERE MVPM1.PTNO = MVPM0.PTNO 
   AND MVPM1.VND_CD = MVPM0.VND_CD 
   AND MVPM1.BRN_CD = MVPM0.BRN_CD
   AND (MVPM1.PMI_PSBL_QTY!=MVPM0.PMI_PSBL_QTY
   OR MVPM1.CMPT_MIL_QTY!=MVPM0.CMPT_MIL_QTY
   OR MVPM1.CMPT_MIL_QTY!=MVPM0.CMPT_MIL_QTY
   OR MVPM1.CMPT_POI_QTY!=MVPM0.CMPT_POI_QTY
   OR MVPM1.PO_PLCY_CD!=MVPM0.PO_PLCY_CD)  
   ;